### ISSUE TITLE
failure to decompile scripts

### ISSUE THREAD

**Issue by Starius65** [mrtenda/CoilSnake#168]
I get this error trying to decompile scripts:
ERROR: Error
Traceback (most recent call last):
  File "coilsnake\ui\common.pyo", line 210, in decompile_script
  File "CCScriptWriter\CCScriptWriter.pyo", line 245, in loadDialogue
ValueError: invalid literal for int() with base 16: 'world'
can't figure out the issue since I have no idea what this is pointing to in the code.

**Comment by ShadowOne333** [comment]
We need more details to be able to tell what's wrong.
First off, what OS are you using?
Second, are you decompiling a clean EB ROM?
We need to know exactly how are you running CoilSnake to be able to pinpoint this problem.

**Comment by ShadowOne333** [comment]
Please, try again with the latest build (commit) of CoilSnake and let us know if it works now.

**Comment by auranunderscore** [comment]
Having similar issue on the latest version. The error I get is
`Error
Traceback (most recent call last):
  File "coilsnake\ui\common.py", line 238, in decompile_script
  File "CCScriptWriter\CCScriptWriter.py", line 206, in loadDialogue
  File "CCScriptWriter\CCScriptWriter.py", line 474, in getText
  File "CCScriptWriter\CCScriptWriter.py", line 595, in getLength
KeyError: 110`
Please advise.

**Comment by PhoenixBound** [comment]
As far as advice goes:

- Decompiling the script isn't something you usually want in most CoilSnake projects. It's useful for fan translations, where you plan to edit a **lot** of the text in the game and keep everything else about the story mostly the same, but for other types of hacks it's usually overkill/wastes a lot of ROM space/is difficult to delete from a project after the fact.
- Decompiling the script may not work properly on CS projects that have had text edits done to them already, or on ROMs that have had text edits made to them. This bug is probably an instance of one of those problems.
- If you want to use normal English EarthBound's script as a reference, an easy way to do that is to create a CoilSnake project that you have no intention of editing (name it `clean` or similar) and decompile the script into that project. That way, you can read all of the original scripts without locking yourself into anything in your romhack.
