### ISSUE TITLE
Question about Staff module

### ISSUE THREAD

**Issue by MAGNAT2645** [mrtenda/CoilSnake#208]
How to put your own font chars to markdown (staff_text.md) ?
Also, i have this staff_text (seems to be fine):
```
> 2

- STAFF
- _____
> 6

# PRODUCED AND DIRECTED BY
- SHIGESATO ITOI
> 2

# WRITTEN BY
- SHIGESATO ITOI
> 2

# MUSIC BY
- KEIICHI SUZUKI
- HIROKAZU TANAKA
> 6

# GAME DESIGNER
- AKIHIKO MIURA
> 2

# ART DIRECTOR
- KOUICHI OOYAMA
> 2

# SOUND DIRECTOR
- HIROKAZU TANAKA
> 2

# PROGRAM DIRECTOR
- SATORU IWATA
> 2

# U.S. CONVERSION DIRECTOR
- KOUJI MALTA
> 2

# TRANSLATION DIRECTORS
- MARCUS LINDBLOM
- MASAYUKI MIURA
> 6

# PROGRAMMERS
- SATORU IWATA
- SATOSHI MITSUHARA
- YOSHIMI TAKAHASHI
- SEIJI OTOGURO
- BOU NAKAJIMA
- SEIKA ABE
- YOSHIKI SUZUKI
- JUN YAMAZAKI
- TOSHIYUKI UENO
- TAKASHI SASAKI
- TAKASHI SAKUMA
- KAZUO SATO
- KOUJI MALTA
> 2

# SOUND PROGRAMMER
- HIROKAZU TANAKA
> 2

# SYSTEM ENGINEERING
- MAKOTO KANAI
- TAKASHI SAKUMA
> 6

# GRAPHICS ARTISTS
- KOUICHI OOYAMA
- HIROYUKI SAKIYAMA
- KOUICHI YAMADA
- MAKIO KATAOKA
- TETSUYA NOTOYA
- YASUNORI YANAGISAWA
> 2

# SPECIAL EFFECTS ARTIST
- TSUNEKAZ ISHIHARA
> 2

# FONT DESIGNERS
- AKIHIKO MIURA
- KOUICHI OOYAMA
> 2

# CONCEPT OF SATURN FONT BY
- SHIGESATO ITOI
> 6

# GRAPHICS DATA MANAGER
- YASUNORI YANAGISAWA
> 2

# MESSAGE DATA MANAGERS
- MASAYUKI MIURA
- HITOSHI MATSUI
> 6

# ADDITIONAL MUSIC COMPOSED BY
- HIROSHI KANAZU
- TOSHIYUKI UENO
> 2

# SOUND STAFF
- TOSHIYUKI UENO
- KOZUE ISHIKAWA
> 6

# ASSISTANT PROGRAMMERS
- IKUHO HAGIYA
- KATSUYOSHI IRIE
> 2

# ASSISTANT GAME DESIGNERS
- KOUICHI OOYAMA
- TAKEHIKO MASUDA
- CHIAKI YOSHIZAWA
- MASAYUKI MIURA
- AKIHITO TODA
- HITOSHI MATSUI
- KATSUYOSHI IRIE
> 2

# ASSISTANT SCENARIO WRITERS
- MASAYUKI MIURA
- AKIHITO TODA
- HIROYUKI JINNAI
> 2

# ENGLISH TEXT WRITERS
- MARCUS LINDBLOM
- DAN OWSEN
> 2

# TRANSLATORS
- KEIKO TAMURA
- YUKA NAKATA
> 6

# CHIEF DEBUGGERS
- TAKUMI AKABANE
- HITOSHI MATSUI
> 6

# NOA DEBUG COORDINATORS
- SEAN O'CONNOR
- MICHAEL KELBAUGH
> 6

# APE DEBUGGING TEAM
- TAKAHIRO NAGAI
- JUNICHI AKAMA
- AKIRA MATSUMOTO
> 6

# NINTENDO DEBUG COORDINATORS
- TOHRU HASHIMOTO
- TATSUYA HISHIDA
> 2

# NINTENDO DEBUGGING TEAM
- KAZUHIDE OHGOE
- ATSUSHI MIYAKE
- HAJIME NAKAMURA
- MAO HAMAMOTO
- MAYUMI TADA
- MAKOTO KEDOUIN
- KIMIKO TSUCHIDA
- SAYAKA KOMURA
> 2

# MAP CHECKERS
- MAPPER KOJIMA
- KATSUYOSHI IRIE
> 6

# SAMPLING VOICES
- SHIGESATO OK? ITOI
- YUKARI WHISTLE SAITO
- HIROKAZU BELCH KOYANO
- ETSUKO VENUS KAWANO
- TAKASHI MU WATANABE
> 2

# OPENING ROCK GUITAR
- M.D.SEEGER
> 6

# HARDWARE SUPPORT
- HIRONOBU KAKUI
- SHIGEKI YAMASHIRO
> 6

# PRODUCTION MANAGERS
- TAKASHI KAWAGUCHI
- KEIZO KATO
- IKUO HYAKUTA
- YUKARI SAITO
> 2

# COORDINATORS
- TAKASHI WATANABE
- RYO KAGAWA
- HIROYUKI JINNAI
- ETSUKO KAWANO
- KAZUYUKI YAMAMOTO
- ATSUKO KAWAHARA
> 6

# SOUND PRODUCERS
- AKIO OHMORI
- RITSUO KAMIMURA
> 6

# SPECIAL THANKS TO
- KENJI ANDO
- MIYUKI KURE
- TAKAYUKI ONODERA
- FUKASHI OMORITA
- YUKIO TAKAHASHI
- KAZUHIKO AMEMIYA
- YASUHIRO KUMAGAI
- YOSHIO HONGO
- NAOKO KANAZAWA
- BENIMARU ITOH
- MOTOHIRO ISHII
- HIROKAZU KOYANO
- MASAO TOTTORI
- NOBUYASU MAKINO
- HIROMI TAMAGAWA
- NANCY YOSHITAKE
> 2

- AND MANY OTHERS
> 6

# THE PRODUCERS WISH TO THANK
- ISHEL ARTVISION
- MOONRIDERS OFFICE
- SEDIC INC.
- SETA CO.,LTD.
- LUCKY NICE
- OKUBO DESIGN STUDIO
- ON ASSOCIATES
- SAI KOUBOU
- ASHURA OFFICE
- SHOGAKUKAN
- SHINCHO SHA
> 6

# CHIEF COORDINATOR
- MARCUS LINDBLOM
> 6

# LINE PRODUCER
- TSUNEKAZ ISHIHARA
> 6

# COPRODUCER
- SATORU IWATA
> 6

# NOA PRODUCER
- MIKE FUKUDA
> 6

# SUPERVISOR
- SHIGERU MIYAMOTO
> 6

# EXECUTIVE PRODUCERS
- HIROSHI YAMAUCHI
- MINORU ARAKAWA
> 6

# PRESENTED BY
- NINTENDO
> 2

# IN ASSOCIATION WITH
- APE INC.
> 2

# AND
- HAL LABORATORY,INC.
> 12

# AND...
#  
> 14

# PLAYER
player_name
> 13
```

but CoilSnake says:
```
Compiling Staff...
'S'

```
and stops compiling.

Another problem is that staff_chars doesn't have space/sections for extra characters.
I have this credits.png
![credits](https://user-images.githubusercontent.com/11666918/64910897-deef3280-d734-11e9-85f7-88723aa95803.png)

So i can't (or i can somehow?) add characters that comes after semicolon.

**Comment by MAGNAT2645** [comment]
I've enabled Debug Mode and now CoilSnake logs:
```
Compiling Staff...
Reading staff character-to-code mapping
Reading staff text
Traceback (most recent call last):
  File "coilsnake\ui\gui.py", line 302, in _do_compile_help
  File "coilsnake\ui\common.py", line 159, in compile_project
  File "coilsnake\modules\eb\StaffModule.py", line 247, in read_from_project
  File "coilsnake\modules\eb\StaffModule.py", line 167, in read_staff_text_from_project
  File "coilsnake\modules\eb\StaffModule.py", line 117, in read_big_line_from_project
  File "coilsnake\modules\eb\StaffModule.py", line 108, in read_text_line_from_project
KeyError: 'S'

'S'

```

**Comment by jamsilva** [comment]
The Staff/staff_chars.yml file contains the mapping from characters to codes. It allows you to add additional entries past 98 and their format is:

```
number:
    Type:      <big or small>
    Row:       <the top row of the character in 8x8 tiles>
    Column:    <the left column of the character in 8x8 tiles>
    Character: <a Unicode code point that is used in staff_text.md>
```

The row and column are, of course, relative to the character position in credits.png.

As for the KeyError: 'S' message, did you remove/replace the entry with "Character: S" from staff_chars.yml?

**Comment by MAGNAT2645** [comment]
Ah, i think i got it. I've replaced all original symbols with codes like "[45]". So i can actually use Unicode symbols like **ж** or **д**?

**Comment by jamsilva** [comment]
Yes, that should work. I did not add support for ccscript-style codes, just single Unicode characters. Let us know how it goes :)

**Comment by MAGNAT2645** [comment]
Thanks, now it works. But is there any way to extend dynamic_names.yml max string length?
